config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get :about, to: "homes#about"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show] do
      collection do
        scope :information do
          get :edit
          patch "/", to: "users#update", as: "update"
        end
        get :unsubscribe
        patch :withdraw
        get :not_active
      end
      member do
        get :calendar_json, to: "users#calendar", defaults: { format: 'json' }
        get :followeds
        get :followers
        get :groups
      end
      resources :follows, only: [:create, :destroy]
    end

    resources :events do
      collection do
        get :favorite
      end
      resources :participants, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resources :members, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root to: "homes#top"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
        get :followeds
        get :followers
        get :groups
      end
      collection do
        delete :destroy_all
      end
    end

    resources :events do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :participants, only: :destroy

    resources :comments, only: [:index, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :groups, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :content, presence: true, length: {maximum: 100}
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @comments = Comment.all.order(created_at: :desc).page(params[:page]).per(@comments_per)
  end

  def active_switch
    @comment = Comment.find(params[:id])
    @comment.update(is_active: !@comment.is_active)
  end

  def destroy
    comment = Comment.find(params[:id])
    event_id = params[:event_id] ? params[:event_id] : nil
    comment.destroy
    if event_id == nil
      redirect_to admin_comments_path, notice: "コメントを削除しました"
    else
      redirect_to admin_event_path(event_id), notice: "コメントを削除しました"
    end
  end

  def destroy_all
    comments = Comment.where(is_active: false)
    comments.destroy_all
    redirect_to admin_comments_path, notice: "無効コメントを全て削除しました"
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_is_active.html.erb
<% if comment.is_active %>
  <%= link_to "有効", active_switch_admin_comment_path(comment.id), method: :patch, id: "active-comment#{comment.id}", class: "btn btn-sm m-1 btn-success", remote: true %>
<% else %>
  <%= link_to "無効", active_switch_admin_comment_path(comment.id), method: :patch, id: "active-comment#{comment.id}", class: "btn btn-sm m-1 btn-danger", remote: true %>
<% end %>

app/views/admin/comments/_list.html.erb
<% if comments.present? %>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th class="col-2">イベント</th>
          <th class="col-2">ユーザー</th>
          <th class="col-6">コメント</th>
          <th class="col-2"></th>
        </tr>
      </thead>
      <tbody>
        <% comments.each do |comment| %>
          <tr>
            <td>
              <%= link_to admin_event_path(comment.event) do %>
                <%= comment.event.name %>
              <% end %>
            </td>
            <td>
              <%= link_to admin_user_path(comment.user) do %>
                <%= comment.user.name %>
              <% end %>
            </td>
            <td>
              <div class="change-color" data-score="<%= comment.score %>">
                <div>score: <%= comment.score%></div>
                <%= comment.content %>
              </div>
            </td>
            <td>
              <span id="comment<%= comment.id %>_active_switch">
                <%= render "admin/comments/is_active", comment: comment %>
              </span>
              <%= link_to "削除", admin_comment_path(comment), method: :delete, id: "del-comment#{comment.id}", class: "btn btn-sm m-1 btn-danger", data: { confirm: "本当に削除しますか？" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-center"><%= paginate comments %></div>
<% else %>
  <div class="col">コメントはありません</div>
<% end %>

app/views/admin/comments/active_switch.js.erb
$("#comment<%= @comment.id %>_active_switch").html("<%= j(render "admin/comments/is_active", comment: @comment) %>");

app/views/admin/comments/index.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6">コメント（<%= @comments.present? ? @comments.total_count : 0 %>）</h2>
  <% if admin_signed_in? %>
    <div class="ml-auto p-2 m-1"><%= link_to "全削除", destroy_all_admin_comments_path, method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "無効コメントを全て削除します。\r\n本当に削除しますか？" } %></div>
  <% end %>
</div>

<%= render "admin/comments/list", comments: @comments %>