config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get :about, to: "homes#about"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show] do
      collection do
        scope :information do
          get :edit
          patch "/", to: "users#update", as: "update"
        end
        get :unsubscribe
        patch :withdraw
        get :not_active
      end
      member do
        get :calendar_json, to: "users#calendar", defaults: { format: 'json' }
        get :followeds
        get :followers
        get :groups
      end
      resources :follows, only: [:create, :destroy]
    end

    resources :events do
      collection do
        get :favorite
      end
      resources :participants, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resources :members, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root to: "homes#top"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
        get :followeds
        get :followers
        get :groups
      end
      collection do
        delete :destroy_all
      end
    end

    resources :events do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :participants, only: :destroy

    resources :comments, only: [:index, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :groups, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]

  has_many :events, dependent: :destroy

  has_many :participants, dependent: :destroy
  has_many :participated_events, through: :participants, source: :event

  has_many :favorites, dependent: :destroy
  has_many :favorite_events, through: :favorites, source: :event

  has_many :comments, dependent: :destroy
  has_many :commented_events, through: :comments, source: :event

  has_many :groups, dependent: :destroy

  has_many :members, dependent: :destroy
  has_many :member_groups, through: :members, source: :group

  has_many :followeds, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, class_name: "Follow", foreign_key: "follower_id" , dependent: :destroy
  has_many :followed_users, through: :followeds, source: :follower
  has_many :follower_users, through: :followers, source: :followed

  has_one_attached :user_image
  validates :user_image, content_type: {in:[:jpg, :jpeg], message: "はjpg, jpegいずれかの形式にして下さい"},
  size: { between: 1.kilobyte..4.megabytes , message: '画像容量が大きすぎます、4MB以下にして下さい' }

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 100}

  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/users/no_user_image.jpeg')
      user_image.attach(io: File.open(file_path), filename: 'user-icon.jpeg', content_type: 'image/jpeg')
    end
    user_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = ENV['GUEST_KEY']
      user.name = "ゲスト"
      user.introduction = "ゲスト用ユーザーです。\r\n退会機能以外に制限はありません。"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all.order(name: :asc).page(params[:page]).per(@users_per)
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
    @participated_events = @user.participated_events

    @since_events = @events.get_since.asc_datetime_order
    @ago_events = @events.get_ago.desc_datetime_order
    @since_participated_events = @participated_events.get_since.asc_datetime_order
    @ago_participated_events = @participated_events.get_ago.desc_datetime_order
    
    @since_events = Kaminari.paginate_array(@since_events).page(params[:since_events_page]).per(@user_show_events_per)
    @ago_events = Kaminari.paginate_array(@ago_events).page(params[:ago_events_page]).per(@user_show_events_per)
    @since_participated_events = Kaminari.paginate_array(@since_participated_events).page(params[:since_participated_events_page]).per(@user_show_events_per)
    @ago_participated_events = Kaminari.paginate_array(@ago_participated_events).page(params[:ago_participated_events_page]).per(@user_show_events_per)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "編集に成功しました。"
    else
      render :edit
    end
  end

  def active_switch
    @user = User.find(params[:id])
    if @user.update(is_active: !@user.is_active)
      events = @user.events.get_since
      events.each do |event|
        event.update(is_active: false)
      end
      groups = @user.groups
      groups.each do |group|
        group.update(is_active: false)
      end
    end
  end

  def followeds
    @users = User.find(params[:id]).followed_users.order(name: :asc).page(params[:page]).per(@users_per)
  end

  def followers
    @users = User.find(params[:id]).follower_users.order(name: :asc).page(params[:page]).per(@users_per)
  end

  def groups
    @user = User.find(params[:id])
    @owner_groups = User.find(params[:id]).groups.order(name: :asc).page(params[:owner_groups_page]).per(@user_groups_per)
    @member_groups = User.find(params[:id]).member_groups.order(name: :asc).page(params[:member_groups_page]).per(@user_groups_per)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path, notice: "ユーザーを削除しました"
  end

  def destroy_all
    users = User.where(is_active: false)
    users.destroy_all
    redirect_to admin_users_path, notice: "退会済ユーザーを全て削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :user_image, :is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/layouts/users/_edit.html.erb
<div class="row no-gutters">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
    <h5 class="test-dark bg-light py-4 mb-0">ユーザー情報編集</h5>
    <div class="form-body p-4">
      <div class="mx-auto text-center">
        <p>各項目を入力してください</p>
      </div>

      <% if user.errors.any? %>
        <ul class="alert alert-danger text-left" role="alert">
          <h6 class="alert-heading">
            入植情報に誤りがあります
          </h6>
        </ul>
      <% end %>

      <% if admin_signed_in? %>
        <%= render "layouts/users/form", user: user, url_path: admin_user_path, action: :patch %>
      <% elsif user_signed_in? %>
        <%= render "layouts/users/form", user: user, url_path: update_users_path, action: :patch %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/users/_event_list.html.erb
<% if events.present? %>
  <table class="table">
    <thead>
      <tr>
        <th colspan="2" class="col-5">イベント名</th>
        <th class="col-2">開催日時</th>
        <th class="col-2">参加人数</th>
        <th class="col-2"></th>
      </tr>
    </thead>
    <tbody>
      <% events.each do |event| %>
        <tr>
          <td>
            <%= image_tag event.get_event_image, size: "80x45", class: "cover-image bg-light", alt: "イベント画像" %>
          </td>
          <td>
            <% if admin_signed_in? %>
              <%= link_to event.name, admin_event_path(event.id) %>
            <% else %>
              <%= link_to event.name, event_path(event.id) %>
            <% end %>
          </td>
          <td><%= event.date.strftime("%m月%d日") %> <%= event.start_time.strftime("%H:%M") %></td>
          <td><%= event.participants.count %> / <%= event.max_people %> 人</td>
          <td class="text-center">
            <% if admin_signed_in? %>
              <span id="event<%= event.id %>_active_switch">
                <%= render "admin/events/is_active", event: event %>
              </span>
              <%= link_to "編集", edit_admin_event_path(event.id), class: "btn btn-sm btn-info m-1" %>
              <%= link_to "削除", admin_event_path(event.id), method: :delete, class: "btn btn-sm btn-danger m-1", data: { confirm: '本当に削除しますか？' } %>
            <% elsif user_signed_in? %>
              <% if current_id?(event.user_id) %>
                <% if event.since_event? %>
                  <%= link_to "編集", edit_event_path(event.id), class: "btn btn-sm btn-info m-1" %>
                <% end %>
                <%= link_to "削除", event_path(event.id), method: :delete, class: "btn btn-sm btn-danger m-1", data: { confirm: '本当に削除しますか？' } %>
              <% else %>
                <%= render "layouts/events/participant", event: event %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="col">イベントはありません</div>
<% end %>

app/views/layouts/users/_follow.html.erb
<% unless current_id?(user.id) %>
  <% unless followed_user?(user.id) %>
    <%= link_to user_follows_path(user), method: :post, remote: true do %>
      <i class="fas fa-lg fa-heart mx-auto off-follow"></i>
    <% end %>
  <% else %>
    <%= link_to user_follow_path(user_id: user.id, id: current_user.id ), method: :delete, remote: true do %>
      <i class="fas fa-lg fa-heart mx-auto on-follow"></i>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/users/_form.html.erb
<%= form_with model: user, url: url_path, method: action, local: true do |f| %>
  <div class="input-group">
    <div class="input-group-prepend col-2 p-0">
      <span class="input-group-text w-100" aria-hidden="true"><i class="fas fa-lg fa-image mx-auto"></i></span>
    </div>
    <%= f.file_field :user_image, class: "form-control p-1 align-items-center", errors: user.errors[:user_image].any?, accept: "image/*" %>
  </div>
  <% if user.errors[:user_image].any? %>
    <%= render "layouts/error_message", object: f.object, attribute: :user_image %>
  <% else %>
    <div class="small text-secondary text-right">※画像はjpg, jpegいずれかの形式にして下さい</div>
  <% end %>

  <div class="input-group mt-3">
    <div class="input-group-prepend col-2 p-0">
      <span class="input-group-text w-100" aria-hidden="true"><i class="fas fa-lg fa-user mx-auto"></i></span>
    </div>
    <%= f.text_field :name, autofocus: true, class: "form-control", errors: user.errors[:name].any?, placeholder: "ユーザー名（2~20文字）" %>
  </div>
  <%= render "layouts/error_message", object: f.object, attribute: :name %>

  <div class="input-group mt-3">
    <div class="input-group-prepend col-2 p-0">
      <span class="input-group-text w-100" aria-hidden="true"><i class="fas fa-lg fa-envelope mx-auto"></i></span>
    </div>
    <%= f.text_field :email, autofocus: true, class: "form-control", errors: user.errors[:email].any?, placeholder: "メールアドレス" %>
  </div>
  <%= render "layouts/error_message", object: f.object, attribute: :email %>

  <div class="input-group mt-3">
    <div class="input-group-prepend col-2 p-0">
      <span class="input-group-text w-100" aria-hidden="true"><i class="fas fa-lg fa-circle-info mx-auto"></i></span>
    </div>
    <%= f.text_area :introduction, class: "form-control", errors: user.errors[:introduction].any?, placeholder: "自己紹介（100文字以内）", size: "40x5" %>
  </div>
  <%= render "layouts/error_message", object: f.object, attribute: :introduction %>

  <% if admin_signed_in? %>
    <div class="input-group mt-3 d-flex justify-content-around">
      <div>
        <%= f.radio_button :is_active, :true, checked: user.is_active %>
        <%= f.label :is_active, "有効", value: :true, class: "mr-3" %>
      </div>
      <div>
        <%= f.radio_button :is_active, :false, checked: !user.is_active %>
        <%= f.label :is_active, "退会", value: :false %>
      </div>
    </div>
  <% end %>
  <%= f.submit "更新", class: "btn btn-block btn-success mt-3" %>
<% end %>

app/views/layouts/users/_groups.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6"><%= user.name %>さんに関するグループ</h2>
  <% if admin_signed_in? %>
    <div class="ml-auto p-2 m-1"><%= link_to "全削除", destroy_all_admin_groups_path, method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "退会済ユーザーを全て削除します。\r\n本当に削除しますか？" } %></div>
  <% elsif user_signed_in? %>
    <div class="ml-auto p-2 m-1">
      <%= link_to "グループ一覧", groups_path, class: "btn btn-sm btn-success" %>
      <%= link_to "グループ作成", new_group_path, class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

<div class="col">
  <div class="d-flex align-items-center mt-4">
    <h4 class="heading col-8 p-0">リーダーグループ（<%= owner_groups.present? ? owner_groups.total_count : 0 %>）</h3>
  </div>
  <%= render "layouts/groups/list", groups: owner_groups %>
  <div class="d-flex justify-content-center">
    <%= paginate owner_groups, param_name: :owner_groups_page %>
  </div>

  <div class="d-flex align-items-center mt-4">
    <h4 class="heading col-8 p-0">参加グループ（<%= member_groups.present? ? member_groups.total_count : 0 %>）</h3>
  </div>
  <%= render "layouts/groups/list", groups: member_groups %>
  <div class="d-flex justify-content-center">
    <%= paginate member_groups, param_name: :member_groups_page %>
  </div
</div>

app/views/layouts/users/_index.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6">ユーザー（<%= users.present? ? users.total_count : 0 %>）</h2>
  <% if admin_signed_in? %>
    <div class="ml-auto p-2 m-1"><%= link_to "全削除", destroy_all_admin_users_path, method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "退会済ユーザーを全て削除します。\r\n本当に削除しますか？" } %></div>
  <% elsif user_signed_in? %>
    <div class="ml-auto p-2 m-1">
      <%= link_to "グループ一覧", groups_path, class: "btn btn-sm btn-success" %>
      <%= link_to "グループ作成", new_group_path, class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

<%= render "layouts/users/list", users: users %>

app/views/layouts/users/_info.html.erb
<div class="col-md-4 col-sm-10 mx-2 mb-auto mx-sm-auto text-center shadow-lg rounded p-4">
  <% if user_signed_in? %>
    <div id="user<%= user.id %>_follow" class="left-top h1">
      <%= render "layouts/users/follow", user: user %>
    </div>
  <% end %>
  <div class="test-dark py-1 mb-0">
    <%= image_tag user.get_user_image(100, 100), size: "100x100", class: "rounded-circle bg-white border border-dark cover-image", alt: "ユーザーアイコン" %>
  </div>

  <div class="form-body">
    <div class="py-3 mx-auto text-center h4 font-weight-bold">
      <%= user.name %>
    </div>

    <% if admin_signed_in? %>
      <div class="d-flex justify-content-around">
        <%= link_to followeds_admin_user_path(user) do %>
          <div>フォロー：<%= user.followed_users.count %></div>
        <% end %>
        <%= link_to followers_admin_user_path(user) do %>
          <div>フォロワー：<%= user.follower_users.count %></div>
        <% end %>
      </div>
      <div>
        <%= link_to groups_admin_user_path(user.id), class: "btn btn-sm border border-secondary rounded mt-3" do %>
          <i class="fas fa-lg fa-user-group"></i>参加グループ
        <% end %>
      </div>
    <% elsif user_signed_in? %>
      <div class="d-flex justify-content-around">
        <%= link_to followeds_user_path(user) do %>
          <div>フォロー：<%= user.followed_users.where(is_active: true).count %></div>
        <% end %>
        <%= link_to followers_user_path(user) do %>
          <div>フォロワー：<span id="follower-num"><%= user.follower_users.where(is_active: true).count %></span></div>
        <% end %>
      </div>
      <div>
        <%= link_to groups_user_path(user.id), class: "btn btn-sm border border-secondary rounded mt-3" do %>
          <i class="fas fa-lg fa-user-group"></i>参加グループ
        <% end %>
      </div>
    <% end %>

    <% if user_signed_in? && current_id?(user.id) %>
      <div>
        <%= link_to favorite_events_path, class: "btn btn-sm border border-secondary rounded mt-3" do %>
          <i class="fas fa-lg fa-star mx-auto on-favorite"></i>お気に入りイベント
        <% end %>
      </div>
    <% end %>

    <div class="text-left mt-3">
      <%= simple_format(user.introduction, sanitize: true) %>
    </div>
  </div>
</div>

app/views/layouts/users/_list.html.erb
<% if users.present? %>
  <div class="card-list-container row no-gutters mx-sm-auto">
    <% users.each do |user| %>
      <div class="col-lg-1 col-md-2 col-sm-4 col-6 px-1 py-3">
        <% if admin_signed_in? %>
          <%= link_to admin_user_path(user.id) do %>
            <%= render "layouts/users/thumbnail", user: user %>
          <% end %>
        <% elsif user_signed_in? %>
          <%= link_to user_path(user.id) do %>
            <%= render "layouts/users/thumbnail", user: user %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center"><%= paginate users %></div>
<% else %>
  <div class="col">ユーザーはいません</div>
<% end %>

app/views/layouts/users/_show.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6">
    <% if user_signed_in? && current_id?(user.id) %>
      マイページ
    <% else %>
      <%= user.name %> さんのページ
    <% end %>
  </h2>
  <% if admin_signed_in? %>
    <div class="ml-auto p-2">
      <span id="user<%= user.id %>_active_switch">
        <%= render "admin/users/is_active", user: user %>
      </span>
      <%= link_to "編集", edit_admin_user_path(user.id), class: "btn btn-sm btn-info m-1" %>
      <%= link_to "削除", admin_user_path(user.id), method: :delete, class: "btn btn-sm btn-danger m-1", data: { confirm: "本当に削除しますか？" } %>
    </div>
  <% elsif user_signed_in? && current_id?(user.id) %>
    <div class="ml-auto p-2 m-1">
      <%= link_to "編集", edit_users_path, class:"btn btn-sm btn-info m-1" %>
      <%= link_to "退会", unsubscribe_users_path, class: "btn btn-sm btn-danger m-1" %>
    </div>
  <% end %>
</div>

<div class="row no-gutters py-4">
  <%= render "layouts/users/info", user: user %>

  <div class="col-md-8 pl-4">
    <% if user_signed_in? && current_id?(user.id) %>
      <div id="calendar" data-user-id="<%= user.id %>" class="my-4"></div>
    <% end %>

    <div class="d-flex align-items-center mt-4">
      <h3 class="heading col-8 p-0">主催イベント（直近 <%= @user_show_events_per %> 件ずつ）</h3>
      <% if user_signed_in? && current_id?(user.id) %>
        <div class="ml-auto p-2"><%= link_to "新規作成", new_event_path, class: "btn btn-sm btn-primary m-1" %></div>
      <% end %>
    </div>
    <%= render "layouts/users/event_list", events: since_events %>
    <div class="d-flex justify-content-center">
      <%= paginate since_events, param_name: :since_events_page %>
    </div>

    <h3 class="heading col-8 p-0 mt-5">
      参加イベント（直近 <%= @user_show_events_per %> 件ずつ）
    </h3>
    <%= render "layouts/users/event_list", events: since_participated_events %>
    <div class="d-flex justify-content-center">
      <%= paginate since_participated_events, param_name: :since_participated_events_page %>
    </div>

    <details class="mt-3">
      <summary>過去イベント</summary>
      <div class="pl-2">
        <h6 class="col-8 heading p-0">主催イベント（直近 <%= @user_show_events_per %> 件ずつ）</h4>
        <%= render "layouts/users/event_list", events: ago_events %>
        <div class="d-flex justify-content-center">
          <%= paginate ago_events, param_name: :ago_events_page %>
        </div>
        <h6 class="col-8 heading p-0">参加イベント（直近 <%= @user_show_events_per %> 件ずつ）</h4>
        <%= render "layouts/users/event_list", events: ago_participated_events %>
        <div class="d-flex justify-content-center">
          <%= paginate ago_participated_events, param_name: :ago_participated_events_page %>
        </div>
      </div>
    </details>
  </div>
</div>

app/views/layouts/users/_thumbnail.html.erb
<div class="card shadow-lg rounde">
  <% if admin_signed_in? %>
    <object id="user<%= user.id %>_active_switch" class="text-center left-top">
      <%= render "admin/users/is_active", user: user %>
    </object>
  <% elsif user_signed_in? && !current_id?(user.id) %>
    <object id="user<%= user.id %>_follow" class="left-top">
      <%= render "layouts/users/follow", user: user %>
    </object>
  <% end %>
  <div class="bg-light p-1">
    <%= image_tag user.get_user_image(50, 50), class: "d-block bg-white mx-auto rounded-circle border border-dark cover-image", alt: "ユーザーアイコン" %>
  </div>
  <div class="p-2 text-center small orverflow-hidden"><%= user.name %></div>
</div>