config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get :about, to: "homes#about"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show] do
      collection do
        scope :information do
          get :edit
          patch "/", to: "users#update", as: "update"
        end
        get :unsubscribe
        patch :withdraw
        get :not_active
      end
      member do
        get :calendar_json, to: "users#calendar", defaults: { format: 'json' }
        get :followeds
        get :followers
        get :groups
      end
      resources :follows, only: [:create, :destroy]
    end

    resources :events do
      collection do
        get :favorite
      end
      resources :participants, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resources :members, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root to: "homes#top"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
        get :followeds
        get :followers
        get :groups
      end
      collection do
        delete :destroy_all
      end
    end

    resources :events do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :participants, only: :destroy

    resources :comments, only: [:index, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :groups, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  include SearchFunctions
  before_action :authenticate_admin!

  def search
    if params[:keyword].empty? || params[:table].nil?
      redirect_to request.referer, alert: "検索ワードを入力してください"
    else
      case params[:table]
      when User.name
        @searches = User.all
        @table = User.name
      when Event.name
        @searches = Event.all
        @table = Event.name
      when Comment.name
        @searches = Comment.all
        @table = Comment.name
      when Group.name
        @searches = Group.all
        @table = Group.name
      else
        @table = nil
      end

      @searches = search_action(@searches, params[:keyword], @table)
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/layouts/searches/_search.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6">検索結果（<%= searches.present? ? searches.total_count : 0 %>）</h2>
</div>

<% if table == User.name %>
  <%= render "layouts/users/list", users: searches %>
<% elsif table == Event.name %>
  <%= render "layouts/events/list", events: searches %>
<% elsif table == Comment.name %>
  <%= render "admin/comments/list", comments: searches %>
<% elsif table == Group.name %>
  <%= render "layouts/groups/list", groups: searches %>
<% end %>

app/views/layouts/searches/_search_box.html.erb
<% if admin_signed_in? %>
  <%= form_with url: admin_search_path, local: true, method: :get, class: "my-1" do |f| %>
    <%= render "layouts/searches/search_form", f: f %>
  <% end %>
<% elsif user_signed_in? %>
  <%= form_with url: search_path, local: true, method: :get, class: "my-1" do |f| %>
    <%= render "layouts/searches/search_form", f: f %>
  <% end %>
<% end %>

app/views/layouts/searches/_search_form.html.erb
<div class="input-group">
    <%= f.search_field :keyword, class: "form-control", placeholder: "検索ワード" %>
  <div class="input-group-append">
    <% if admin_signed_in? %>
      <%= f.select :table, [["ユーザー", User.name], ["イベント", Event.name], ["コメント", Comment.name], ["グループ", Group.name]], selected: params[:table] %>
    <% elsif user_signed_in? %>
      <%= f.select :table, [["ユーザー", User.name], ["イベント", Event.name], ["グループ", Group.name]], selected: params[:table] %>
    <% end %>
    <%= button_tag type: "submit", class: "btn btn-secondary" do %>
      <i class="fas fa-lg fa-magnifying-glass" aria-hidden="true"></i>
    <% end %>
  </div>
</div>