config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get :about, to: "homes#about"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show] do
      collection do
        scope :information do
          get :edit
          patch "/", to: "users#update", as: "update"
        end
        get :unsubscribe
        patch :withdraw
        get :not_active
      end
      member do
        get :calendar_json, to: "users#calendar", defaults: { format: 'json' }
        get :followeds
        get :followers
        get :groups
      end
      resources :follows, only: [:create, :destroy]
    end

    resources :events do
      collection do
        get :favorite
      end
      resources :participants, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resources :members, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root to: "homes#top"
    get :search, to: "searches#search"

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
        get :followeds
        get :followers
        get :groups
      end
      collection do
        delete :destroy_all
      end
    end

    resources :events do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :participants, only: :destroy

    resources :comments, only: [:index, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end

    resources :groups, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :active_switch
      end
      collection do
        delete :destroy_all
      end
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_one_attached :group_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: { scope: :is_active }
  validates :introduction, length: {maximum: 200}
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @groups = Group.all
    @groups = Kaminari.paginate_array(@groups).page(params[:page]).per(@groups_per)
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to admin_group_path(@group), notice: "更新しました"
    else
      render :edit
    end
  end

  def active_switch
    @group = Group.find(params[:id])
    @group.update(is_active: !@group.is_active)
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to admin_groups_path, notice: "グループを削除しました"
  end

  def destroy_all
    groups = Group.where(is_active: false)
    groups.destroy_all
    redirect_to admin_groups_path, notice: "無効グループを全て削除しました"
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/layouts/groups/_be_member.html.erb
<% unless current_id?(group.user_id) %>
  <% unless member_group?(group.id) %>
    <%= link_to "参加する", group_members_path(group_id: group.id), method: :post, class: "btn btn-sm btn-success" %>
  <% else %>
    <%= link_to "参加取消", group_member_path(group_id: group.id, id: current_user.id ), method: :delete, class: "btn btn-sm btn-danger" %>
  <% end %>
<% end %>

app/views/layouts/groups/_edit.html.erb
<div class="row no-gutters">
  <div class="col-md-8 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
    <h5 class="test-dark bg-light py-4 mb-0">グループ編集</h5>

    <% if admin_signed_in? %>
      <%= render "layouts/groups/form", group: group, url_path: admin_group_path %>
    <% elsif user_signed_in? %>
      <%= render "layouts/groups/form", group: group, url_path: group_path %>
    <% end %>
  </div>
</div>

app/views/layouts/groups/_form.html.erb
<div class="form-body p-4">
  <div class="mx-auto text-center">
    <p>各項目を入力してください</p>
  </div>

  <% if group.errors.any? %>
    <ul class="alert alert-danger text-left" role="alert">
      <h6 class="alert-heading">
        入力情報に誤りがあります
      </h6>
    </ul>
  <% end %>

  <%= form_with model: group, url: url_path, local: true do |f| %>

    <div class="input-group">
      <div class="input-group-prepend col-2 p-0">
        <span class="input-group-text w-100" aria-hidden="true"><i class="fas fa-lg fa-people-group mx-auto"></i></span>
      </div>
      <%= f.text_field :name, autofocus: true, class: "form-control", errors: group.errors[:name].any?, placeholder: "グループ名" %>
    </div>
    <%= render "layouts/error_message", object: f.object, attribute: :name %>

    <div class="input-group mt-3">
      <div class="input-group-prepend col-2 p-0">
      <span class="input-group-text w-100" aria-hidden="true"><i class="fas fa-lg fa-circle-info mx-auto"></i></span>
      </div>
      <%= f.text_area :introduction, class: "form-control", errors: group.errors[:introduction].any?, placeholder: "説明", size: "40x5" %>
    </div>
    <%= render "layouts/error_message", object: f.object, attribute: :introduction %>

    <%= f.submit class:"btn btn-block btn-success mt-3" %>
  <% end %>
</div>

app/views/layouts/groups/_index.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6">グループ（<%= groups.present? ? groups.total_count : 0 %>）</h2>
  <% if admin_signed_in? %>
    <div class="ml-auto p-2 m-1"><%= link_to "全削除", destroy_all_admin_groups_path, method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "退会済ユーザーを全て削除します。\r\n本当に削除しますか？" } %></div>
  <% elsif user_signed_in? %>
    <div class="ml-auto p-2 m-1">
      <%= link_to "グループ作成", new_group_path, class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

<div class="col">
  <%= render "layouts/groups/list", groups: groups %>
  <div class="d-flex justify-content-center"><%= paginate groups %></div>
</div>

app/views/layouts/groups/_leader.html.erb
<%= image_tag user.get_user_image(40, 40), size: "40x40", class: "rounded-circle bg-white border border-dark cover-image mr-2", alt: "ユーザーアイコン" %>
<%= user.name %>

app/views/layouts/groups/_list.html.erb
<% if groups.present? %>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th class="col-2">グループ名</th>
          <th class="col-2">リーダー</th>
          <th class="col-6">メンバー</th>
          <th class="col-2"></th>
        </tr>
      </thead>
      <tbody>
        <% groups.each do |group| %>
          <tr>
            <td>
              <% if admin_signed_in? %>
                <%= link_to group.name, admin_group_path(group.id) %>
              <% elsif user_signed_in? %>
                <%= link_to group.name, group_path(group.id) %>
              <% end %>
            </td>
            <td>
              <% if admin_signed_in? %>
                <%= link_to admin_user_path(group.user.id) do %>
                  <%= render "layouts/groups/leader", user: group.user %>
                <% end %>
              <% elsif user_signed_in? %>
                <%= link_to user_path(group.user.id) do %>
                  <%= render "layouts/groups/leader", user: group.user %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% group.users.each do |user| %>
                <% if admin_signed_in? %>
                  <%= link_to admin_user_path(user.id) do %>
                    <%= render "layouts/groups/member", user: user %>
                  <% end %>
                <% elsif user_signed_in? %>
                  <%= link_to user_path(user.id) do %>
                    <%= render "layouts/groups/member", user: user %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% if admin_signed_in? %>
                <span id="group<%= group.id %>_active_switch">
                  <%= render "admin/groups/is_active", group: group %>
                </span>
                <%= link_to "削除", admin_group_path(group.id), method: :delete, id: "del-group#{group.id}", class: "btn btn-sm btn-danger m-1" , data: { confirm: "本当に削除しますか？" } %>
              <% elsif user_signed_in? %>
                <% if current_id?(group.user_id) %>
                  <%= link_to "編集", edit_group_path(group.id), class: "btn btn-sm btn-success m-1" %>
                  <%= link_to "削除", group_path(group.id), method: :delete, class: "btn btn-sm btn-danger m-1" , data: { confirm: "本当に削除しますか？" } %>
                <% end %>
                <%= render "layouts/groups/be_member", group: group %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="col">グループはありません</div>
<% end %>

app/views/layouts/groups/_member.html.erb
<%= image_tag user.get_user_image(20, 20), size: "20x20", class: "rounded-circle bg-white border border-dark cover-image", alt: "ユーザーアイコン" %>
<%= user.name %>

app/views/layouts/groups/_show.html.erb
<div class="d-flex align-items-center">
  <h2 class="heading col-lg-8 col-md-6">
    <%= group.name %>
  </h2>
  <div class="ml-auto p-2 m-1">
    <% if admin_signed_in? %>
      <span id="group<%= group.id %>_active_switch">
        <%= render "admin/groups/is_active", group: group %>
      </span>
      <%= link_to "編集", edit_admin_group_path(group.id), class: "btn btn-sm btn-info m-1" %>
      <%= link_to "削除", admin_group_path(group.id), method: :delete, id: "del-group#{group.id}", class: "btn btn-sm btn-danger m-1", data: { confirm: "本当に削除しますか？" } %>
    <% elsif user_signed_in? && current_id?(group.user_id) %>
      <%= link_to "編集", edit_group_path(group.id), class:"btn btn-sm btn-info m-1" %>
      <%= link_to "削除", group_path(group.id), method: :delete, id: "del-group#{group.id}", class: "btn btn-sm btn-danger m-1", data: { confirm: "本当に削除しますか？" } %>
    <% else %>
      <%= render "layouts/groups/be_member", group: group %>
    <% end %>
  </div>
</div>

<div class="my-5 col"><%= group.introduction %></div>

<div class="col d-flex justify-content-center">
  <table class="table px-3">
    <thead>
      <tr>
        <th>
          <% if admin_signed_in? %>
            <%= link_to admin_user_path(group.user.id) do %>
              <%= render "layouts/groups/leader", user: group.user %>（リーダー）
            <% end %>
          <% elsif user_signed_in? %>
            <%= link_to user_path(group.user.id) do %>
              <%= render "layouts/groups/leader", user: group.user %>（リーダー）
            <% end %>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% if group.users.present? %>
        <% group.users.each do |user| %>
          <tr>
            <td>
              <% if admin_signed_in? %>
                <%= link_to admin_user_path(group.user.id) do %>
                  <%= render "layouts/groups/member", user: user %>
                <% end %>
              <% elsif user_signed_in? %>
                <%= link_to user_path(group.user.id) do %>
                  <%= render "layouts/groups/member", user: user %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        メンバーはいません
      <% end %>
    </tbody>
  </table>
</div>